services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: "jellyfin"

    restart: unless-stopped

    group_add:
      - ${VIDEO_GROUP}

    hostname: ${HOSTNAME}

    networks:
      - intranet
      - internet

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

    volumes:
      - ${LOGS_DIR}:/config/log
      - ${CONFIG_DIR}:/config/config
      - ${TRANSCODES_DIR}:/transcodes
      - ${CACHE_DIR}:/cache
      - ${MEDIA_DIR}:/media

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  intranet:
    external: true
    name: ${INTERNAL_NETWORK_NAME}

  internet:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}
