services:
  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: "immich-server"

    restart: unless-stopped

    command: ["start.sh", "immich"]

    volumes:
      - ${UPLOAD_DIR}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    environment:
      UPLOAD_DIR: ${UPLOAD_DIR}

      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}

      REDIS_HOSTNAME: ${REDIS_HOSTNAME}

    env_file:
      - ${SECRETS_FILE}

    networks:
      - intranet
      - immich

    depends_on:
      - redis
      - database

  microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: "immich-microservices"

    restart: unless-stopped

    command: ["start.sh", "microservices"]

    networks:
      - immich

    volumes:
      - ${UPLOAD_DIR}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    environment:
      UPLOAD_DIR: ${UPLOAD_DIR}

      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}

      REDIS_HOSTNAME: ${REDIS_HOSTNAME}

    env_file:
      - ${SECRETS_FILE}

    depends_on:
      - redis
      - database

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: "immich-machine-learning"

    restart: unless-stopped

    networks:
      - immich

    volumes:
      - ${CACHE_DIR}:/cache

    env_file:
      - ${SECRETS_FILE}

  redis:
    image: redis:6.2-alpine
    container_name: ${REDIS_HOSTNAME}

    restart: unless-stopped

    networks:
      - immich

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: ${DB_HOSTNAME}

    restart: unless-stopped

    networks:
      - immich

    env_file:
      - ${SECRETS_FILE}

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}

    volumes:
      - ${DB_DIR}:/var/lib/postgresql/data

networks:
  immich:

  intranet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
